import Head from "next/head";
import Image from "next/image";
// import styles from "@/styles/BoxStyle.module.css";
export default function ReportTerminatedParticipant() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "400px",
          height: "400px",
          backgroundColor: "lightpink",
          display: "flex",
          alignContent: "center",
          alignItems: "center",
          justifyContent: "space-around",
          border: "8px solid seagreen",
        }}
      >
        Terminated Participant Report
      </div>
    </>
  );
}
